// <auto-generated />
using System;
using HealthcareClaimsQueue.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthcareClaimsQueue.API.Migrations
{
    [DbContext(typeof(QueueDbContext))]
    [Migration("20260929064336_AddPendedAtField")]
    partial class AddPendedAtField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK_app_user");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<decimal>("BilledAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("billed_amount");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("claim_number");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("member_id");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("ReceivedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_on");

                    b.Property<DateTime>("ServiceFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("service_from");

                    b.Property<DateTime>("ServiceTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("service_to");

                    b.HasKey("ClaimId")
                        .HasName("PK_claim");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.ToTable("claim", (string)null);
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.Queue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("queue_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueueId"));

                    b.Property<string>("QueueCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("queue_code");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("queue_name");

                    b.HasKey("QueueId")
                        .HasName("PK_queue");

                    b.HasIndex("QueueCode")
                        .IsUnique();

                    b.ToTable("queue", (string)null);
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.ReviewTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("closed_at");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<DateTime?>("LockExpiresOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("lock_expires_on");

                    b.Property<int?>("LockedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("locked_by_user_id");

                    b.Property<DateTime?>("LockedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_on");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<string>("Outcome")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("outcome");

                    b.Property<DateTime?>("PendedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint")
                        .HasColumnName("priority");

                    b.Property<int>("QueueId")
                        .HasColumnType("int")
                        .HasColumnName("queue_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("TaskId")
                        .HasName("PK_review_task");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_review_task_claim");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("QueueId", "Status")
                        .HasDatabaseName("ix_review_task_queue_status");

                    b.ToTable("review_task", (string)null);
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.UserSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("PK_user_session");

                    b.HasIndex("UserId");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.ReviewTask", b =>
                {
                    b.HasOne("HealthcareClaimsQueue.API.Models.AppUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthcareClaimsQueue.API.Models.AppUser", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthcareClaimsQueue.API.Models.Claim", "Claim")
                        .WithMany("ReviewTasks")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthcareClaimsQueue.API.Models.AppUser", "ClosedByUser")
                        .WithMany("CompletedTasks")
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthcareClaimsQueue.API.Models.AppUser", "LockedByUser")
                        .WithMany("LockedTasks")
                        .HasForeignKey("LockedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthcareClaimsQueue.API.Models.Queue", "Queue")
                        .WithMany("ReviewTasks")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Claim");

                    b.Navigation("ClosedByUser");

                    b.Navigation("LockedByUser");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.UserSession", b =>
                {
                    b.HasOne("HealthcareClaimsQueue.API.Models.AppUser", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.AppUser", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CompletedTasks");

                    b.Navigation("LockedTasks");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.Claim", b =>
                {
                    b.Navigation("ReviewTasks");
                });

            modelBuilder.Entity("HealthcareClaimsQueue.API.Models.Queue", b =>
                {
                    b.Navigation("ReviewTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
